/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppContributeRouteImport } from './routes/_app/contribute'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiV1RouteRouteImport } from './routes/api/v1/route'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as ExtensionConnectRouteImport } from './routes/extension.connect'
import { Route as MediaSplatRouteImport } from './routes/media/$'
import { Route as AppAppsSlugRouteImport } from './routes/_app/apps.$slug'
import { Route as AppBrowsePlatformRouteImport } from './routes/_app/browse.$platform'
import { Route as AppFlowsIdRouteImport } from './routes/_app/flows.$id'
import { Route as AppSavedIndexRouteImport } from './routes/_app/saved.index'
import { Route as AppSavedIdRouteImport } from './routes/_app/saved.$id'
import { Route as AppScreensIdRouteImport } from './routes/_app/screens.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiV1AppsRouteImport } from './routes/api/v1/apps'
import { Route as ApiV1CapturesRouteImport } from './routes/api/v1/captures'
import { Route as ApiV1CollectionsRouteImport } from './routes/api/v1/collections'
import { Route as ApiV1FlowsRouteImport } from './routes/api/v1/flows'
import { Route as ApiV1KeysRouteImport } from './routes/api/v1/keys'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1ReviewRouteImport } from './routes/api/v1/review'
import { Route as ApiV1SavesRouteImport } from './routes/api/v1/saves'
import { Route as ApiV1ScreensRouteImport } from './routes/api/v1/screens'
import { Route as ApiV1SearchRouteImport } from './routes/api/v1/search'
import { Route as ApiV1TaxonomyRouteImport } from './routes/api/v1/taxonomy'
import { Route as ApiV1AppsSlugRouteImport } from './routes/api/v1/apps.$slug'
import { Route as ApiV1CollectionsIdRouteImport } from './routes/api/v1/collections.$id'
import { Route as ApiV1FlowsIdRouteImport } from './routes/api/v1/flows.$id'
import { Route as ApiV1KeysIdRouteImport } from './routes/api/v1/keys.$id'
import { Route as ApiV1ScreensIdRouteImport } from './routes/api/v1/screens.$id'
import { Route as ApiV1AdminMediaBackfillRouteImport } from './routes/api/v1/admin.media.backfill'
import { Route as ApiV1CollectionsIdItemsRouteImport } from './routes/api/v1/collections.$id.items'
import { Route as ApiV1ReviewKindIdRouteImport } from './routes/api/v1/review.$kind.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContributeRoute = AppContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1RouteRoute = ApiV1RouteRouteImport.update({
  id: '/api/v1',
  path: '/api/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const ExtensionConnectRoute = ExtensionConnectRouteImport.update({
  id: '/extension/connect',
  path: '/extension/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppsSlugRoute = AppAppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowsePlatformRoute = AppBrowsePlatformRouteImport.update({
  id: '/browse/$platform',
  path: '/browse/$platform',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsIdRoute = AppFlowsIdRouteImport.update({
  id: '/flows/$id',
  path: '/flows/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedIndexRoute = AppSavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedIdRoute = AppSavedIdRouteImport.update({
  id: '/saved/$id',
  path: '/saved/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppScreensIdRoute = AppScreensIdRouteImport.update({
  id: '/screens/$id',
  path: '/screens/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1AppsRoute = ApiV1AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1CapturesRoute = ApiV1CapturesRouteImport.update({
  id: '/captures',
  path: '/captures',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1CollectionsRoute = ApiV1CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1FlowsRoute = ApiV1FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1KeysRoute = ApiV1KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1ReviewRoute = ApiV1ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1SavesRoute = ApiV1SavesRouteImport.update({
  id: '/saves',
  path: '/saves',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1ScreensRoute = ApiV1ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1SearchRoute = ApiV1SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1TaxonomyRoute = ApiV1TaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1AppsSlugRoute = ApiV1AppsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiV1AppsRoute,
} as any)
const ApiV1CollectionsIdRoute = ApiV1CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1CollectionsRoute,
} as any)
const ApiV1FlowsIdRoute = ApiV1FlowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1FlowsRoute,
} as any)
const ApiV1KeysIdRoute = ApiV1KeysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1KeysRoute,
} as any)
const ApiV1ScreensIdRoute = ApiV1ScreensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1ScreensRoute,
} as any)
const ApiV1AdminMediaBackfillRoute = ApiV1AdminMediaBackfillRouteImport.update({
  id: '/admin/media/backfill',
  path: '/admin/media/backfill',
  getParentRoute: () => ApiV1RouteRoute,
} as any)
const ApiV1CollectionsIdItemsRoute = ApiV1CollectionsIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => ApiV1CollectionsIdRoute,
} as any)
const ApiV1ReviewKindIdRoute = ApiV1ReviewKindIdRouteImport.update({
  id: '/$kind/$id',
  path: '/$kind/$id',
  getParentRoute: () => ApiV1ReviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/mcp': typeof McpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/v1': typeof ApiV1RouteRouteWithChildren
  '/contribute': typeof AppContributeRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/media/$': typeof MediaSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/apps/$slug': typeof AppAppsSlugRoute
  '/browse/$platform': typeof AppBrowsePlatformRoute
  '/flows/$id': typeof AppFlowsIdRoute
  '/saved/$id': typeof AppSavedIdRoute
  '/screens/$id': typeof AppScreensIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/apps': typeof ApiV1AppsRouteWithChildren
  '/api/v1/captures': typeof ApiV1CapturesRoute
  '/api/v1/collections': typeof ApiV1CollectionsRouteWithChildren
  '/api/v1/flows': typeof ApiV1FlowsRouteWithChildren
  '/api/v1/keys': typeof ApiV1KeysRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/review': typeof ApiV1ReviewRouteWithChildren
  '/api/v1/saves': typeof ApiV1SavesRoute
  '/api/v1/screens': typeof ApiV1ScreensRouteWithChildren
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1/taxonomy': typeof ApiV1TaxonomyRoute
  '/saved/': typeof AppSavedIndexRoute
  '/api/v1/apps/$slug': typeof ApiV1AppsSlugRoute
  '/api/v1/collections/$id': typeof ApiV1CollectionsIdRouteWithChildren
  '/api/v1/flows/$id': typeof ApiV1FlowsIdRoute
  '/api/v1/keys/$id': typeof ApiV1KeysIdRoute
  '/api/v1/screens/$id': typeof ApiV1ScreensIdRoute
  '/api/v1/admin/media/backfill': typeof ApiV1AdminMediaBackfillRoute
  '/api/v1/collections/$id/items': typeof ApiV1CollectionsIdItemsRoute
  '/api/v1/review/$kind/$id': typeof ApiV1ReviewKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/v1': typeof ApiV1RouteRouteWithChildren
  '/contribute': typeof AppContributeRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/media/$': typeof MediaSplatRoute
  '/docs': typeof DocsIndexRoute
  '/apps/$slug': typeof AppAppsSlugRoute
  '/browse/$platform': typeof AppBrowsePlatformRoute
  '/flows/$id': typeof AppFlowsIdRoute
  '/saved/$id': typeof AppSavedIdRoute
  '/screens/$id': typeof AppScreensIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/apps': typeof ApiV1AppsRouteWithChildren
  '/api/v1/captures': typeof ApiV1CapturesRoute
  '/api/v1/collections': typeof ApiV1CollectionsRouteWithChildren
  '/api/v1/flows': typeof ApiV1FlowsRouteWithChildren
  '/api/v1/keys': typeof ApiV1KeysRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/review': typeof ApiV1ReviewRouteWithChildren
  '/api/v1/saves': typeof ApiV1SavesRoute
  '/api/v1/screens': typeof ApiV1ScreensRouteWithChildren
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1/taxonomy': typeof ApiV1TaxonomyRoute
  '/saved': typeof AppSavedIndexRoute
  '/api/v1/apps/$slug': typeof ApiV1AppsSlugRoute
  '/api/v1/collections/$id': typeof ApiV1CollectionsIdRouteWithChildren
  '/api/v1/flows/$id': typeof ApiV1FlowsIdRoute
  '/api/v1/keys/$id': typeof ApiV1KeysIdRoute
  '/api/v1/screens/$id': typeof ApiV1ScreensIdRoute
  '/api/v1/admin/media/backfill': typeof ApiV1AdminMediaBackfillRoute
  '/api/v1/collections/$id/items': typeof ApiV1CollectionsIdItemsRoute
  '/api/v1/review/$kind/$id': typeof ApiV1ReviewKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/mcp': typeof McpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/v1': typeof ApiV1RouteRouteWithChildren
  '/_app/contribute': typeof AppContributeRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/media/$': typeof MediaSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/_app/apps/$slug': typeof AppAppsSlugRoute
  '/_app/browse/$platform': typeof AppBrowsePlatformRoute
  '/_app/flows/$id': typeof AppFlowsIdRoute
  '/_app/saved/$id': typeof AppSavedIdRoute
  '/_app/screens/$id': typeof AppScreensIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/apps': typeof ApiV1AppsRouteWithChildren
  '/api/v1/captures': typeof ApiV1CapturesRoute
  '/api/v1/collections': typeof ApiV1CollectionsRouteWithChildren
  '/api/v1/flows': typeof ApiV1FlowsRouteWithChildren
  '/api/v1/keys': typeof ApiV1KeysRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/review': typeof ApiV1ReviewRouteWithChildren
  '/api/v1/saves': typeof ApiV1SavesRoute
  '/api/v1/screens': typeof ApiV1ScreensRouteWithChildren
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1/taxonomy': typeof ApiV1TaxonomyRoute
  '/_app/saved/': typeof AppSavedIndexRoute
  '/api/v1/apps/$slug': typeof ApiV1AppsSlugRoute
  '/api/v1/collections/$id': typeof ApiV1CollectionsIdRouteWithChildren
  '/api/v1/flows/$id': typeof ApiV1FlowsIdRoute
  '/api/v1/keys/$id': typeof ApiV1KeysIdRoute
  '/api/v1/screens/$id': typeof ApiV1ScreensIdRoute
  '/api/v1/admin/media/backfill': typeof ApiV1AdminMediaBackfillRoute
  '/api/v1/collections/$id/items': typeof ApiV1CollectionsIdItemsRoute
  '/api/v1/review/$kind/$id': typeof ApiV1ReviewKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/mcp'
    | '/sign-in'
    | '/sign-up'
    | '/api/v1'
    | '/contribute'
    | '/review'
    | '/search'
    | '/settings'
    | '/docs/$slug'
    | '/extension/connect'
    | '/media/$'
    | '/docs/'
    | '/apps/$slug'
    | '/browse/$platform'
    | '/flows/$id'
    | '/saved/$id'
    | '/screens/$id'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1/apps'
    | '/api/v1/captures'
    | '/api/v1/collections'
    | '/api/v1/flows'
    | '/api/v1/keys'
    | '/api/v1/me'
    | '/api/v1/review'
    | '/api/v1/saves'
    | '/api/v1/screens'
    | '/api/v1/search'
    | '/api/v1/taxonomy'
    | '/saved/'
    | '/api/v1/apps/$slug'
    | '/api/v1/collections/$id'
    | '/api/v1/flows/$id'
    | '/api/v1/keys/$id'
    | '/api/v1/screens/$id'
    | '/api/v1/admin/media/backfill'
    | '/api/v1/collections/$id/items'
    | '/api/v1/review/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/sign-in'
    | '/sign-up'
    | '/api/v1'
    | '/contribute'
    | '/review'
    | '/search'
    | '/settings'
    | '/docs/$slug'
    | '/extension/connect'
    | '/media/$'
    | '/docs'
    | '/apps/$slug'
    | '/browse/$platform'
    | '/flows/$id'
    | '/saved/$id'
    | '/screens/$id'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1/apps'
    | '/api/v1/captures'
    | '/api/v1/collections'
    | '/api/v1/flows'
    | '/api/v1/keys'
    | '/api/v1/me'
    | '/api/v1/review'
    | '/api/v1/saves'
    | '/api/v1/screens'
    | '/api/v1/search'
    | '/api/v1/taxonomy'
    | '/saved'
    | '/api/v1/apps/$slug'
    | '/api/v1/collections/$id'
    | '/api/v1/flows/$id'
    | '/api/v1/keys/$id'
    | '/api/v1/screens/$id'
    | '/api/v1/admin/media/backfill'
    | '/api/v1/collections/$id/items'
    | '/api/v1/review/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/docs'
    | '/mcp'
    | '/sign-in'
    | '/sign-up'
    | '/api/v1'
    | '/_app/contribute'
    | '/_app/review'
    | '/_app/search'
    | '/_app/settings'
    | '/docs/$slug'
    | '/extension/connect'
    | '/media/$'
    | '/docs/'
    | '/_app/apps/$slug'
    | '/_app/browse/$platform'
    | '/_app/flows/$id'
    | '/_app/saved/$id'
    | '/_app/screens/$id'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1/apps'
    | '/api/v1/captures'
    | '/api/v1/collections'
    | '/api/v1/flows'
    | '/api/v1/keys'
    | '/api/v1/me'
    | '/api/v1/review'
    | '/api/v1/saves'
    | '/api/v1/screens'
    | '/api/v1/search'
    | '/api/v1/taxonomy'
    | '/_app/saved/'
    | '/api/v1/apps/$slug'
    | '/api/v1/collections/$id'
    | '/api/v1/flows/$id'
    | '/api/v1/keys/$id'
    | '/api/v1/screens/$id'
    | '/api/v1/admin/media/backfill'
    | '/api/v1/collections/$id/items'
    | '/api/v1/review/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  McpRoute: typeof McpRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiV1RouteRoute: typeof ApiV1RouteRouteWithChildren
  ExtensionConnectRoute: typeof ExtensionConnectRoute
  MediaSplatRoute: typeof MediaSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contribute': {
      id: '/_app/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof AppContributeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1': {
      id: '/api/v1'
      path: '/api/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/extension/connect': {
      id: '/extension/connect'
      path: '/extension/connect'
      fullPath: '/extension/connect'
      preLoaderRoute: typeof ExtensionConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/apps/$slug': {
      id: '/_app/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppAppsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/$platform': {
      id: '/_app/browse/$platform'
      path: '/browse/$platform'
      fullPath: '/browse/$platform'
      preLoaderRoute: typeof AppBrowsePlatformRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows/$id': {
      id: '/_app/flows/$id'
      path: '/flows/$id'
      fullPath: '/flows/$id'
      preLoaderRoute: typeof AppFlowsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved/': {
      id: '/_app/saved/'
      path: '/saved'
      fullPath: '/saved/'
      preLoaderRoute: typeof AppSavedIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved/$id': {
      id: '/_app/saved/$id'
      path: '/saved/$id'
      fullPath: '/saved/$id'
      preLoaderRoute: typeof AppSavedIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screens/$id': {
      id: '/_app/screens/$id'
      path: '/screens/$id'
      fullPath: '/screens/$id'
      preLoaderRoute: typeof AppScreensIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/apps': {
      id: '/api/v1/apps'
      path: '/apps'
      fullPath: '/api/v1/apps'
      preLoaderRoute: typeof ApiV1AppsRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/captures': {
      id: '/api/v1/captures'
      path: '/captures'
      fullPath: '/api/v1/captures'
      preLoaderRoute: typeof ApiV1CapturesRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/collections': {
      id: '/api/v1/collections'
      path: '/collections'
      fullPath: '/api/v1/collections'
      preLoaderRoute: typeof ApiV1CollectionsRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/flows': {
      id: '/api/v1/flows'
      path: '/flows'
      fullPath: '/api/v1/flows'
      preLoaderRoute: typeof ApiV1FlowsRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/keys': {
      id: '/api/v1/keys'
      path: '/keys'
      fullPath: '/api/v1/keys'
      preLoaderRoute: typeof ApiV1KeysRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/review': {
      id: '/api/v1/review'
      path: '/review'
      fullPath: '/api/v1/review'
      preLoaderRoute: typeof ApiV1ReviewRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/saves': {
      id: '/api/v1/saves'
      path: '/saves'
      fullPath: '/api/v1/saves'
      preLoaderRoute: typeof ApiV1SavesRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/screens': {
      id: '/api/v1/screens'
      path: '/screens'
      fullPath: '/api/v1/screens'
      preLoaderRoute: typeof ApiV1ScreensRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/search': {
      id: '/api/v1/search'
      path: '/search'
      fullPath: '/api/v1/search'
      preLoaderRoute: typeof ApiV1SearchRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/taxonomy': {
      id: '/api/v1/taxonomy'
      path: '/taxonomy'
      fullPath: '/api/v1/taxonomy'
      preLoaderRoute: typeof ApiV1TaxonomyRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/apps/$slug': {
      id: '/api/v1/apps/$slug'
      path: '/$slug'
      fullPath: '/api/v1/apps/$slug'
      preLoaderRoute: typeof ApiV1AppsSlugRouteImport
      parentRoute: typeof ApiV1AppsRoute
    }
    '/api/v1/collections/$id': {
      id: '/api/v1/collections/$id'
      path: '/$id'
      fullPath: '/api/v1/collections/$id'
      preLoaderRoute: typeof ApiV1CollectionsIdRouteImport
      parentRoute: typeof ApiV1CollectionsRoute
    }
    '/api/v1/flows/$id': {
      id: '/api/v1/flows/$id'
      path: '/$id'
      fullPath: '/api/v1/flows/$id'
      preLoaderRoute: typeof ApiV1FlowsIdRouteImport
      parentRoute: typeof ApiV1FlowsRoute
    }
    '/api/v1/keys/$id': {
      id: '/api/v1/keys/$id'
      path: '/$id'
      fullPath: '/api/v1/keys/$id'
      preLoaderRoute: typeof ApiV1KeysIdRouteImport
      parentRoute: typeof ApiV1KeysRoute
    }
    '/api/v1/screens/$id': {
      id: '/api/v1/screens/$id'
      path: '/$id'
      fullPath: '/api/v1/screens/$id'
      preLoaderRoute: typeof ApiV1ScreensIdRouteImport
      parentRoute: typeof ApiV1ScreensRoute
    }
    '/api/v1/admin/media/backfill': {
      id: '/api/v1/admin/media/backfill'
      path: '/admin/media/backfill'
      fullPath: '/api/v1/admin/media/backfill'
      preLoaderRoute: typeof ApiV1AdminMediaBackfillRouteImport
      parentRoute: typeof ApiV1RouteRoute
    }
    '/api/v1/collections/$id/items': {
      id: '/api/v1/collections/$id/items'
      path: '/items'
      fullPath: '/api/v1/collections/$id/items'
      preLoaderRoute: typeof ApiV1CollectionsIdItemsRouteImport
      parentRoute: typeof ApiV1CollectionsIdRoute
    }
    '/api/v1/review/$kind/$id': {
      id: '/api/v1/review/$kind/$id'
      path: '/$kind/$id'
      fullPath: '/api/v1/review/$kind/$id'
      preLoaderRoute: typeof ApiV1ReviewKindIdRouteImport
      parentRoute: typeof ApiV1ReviewRoute
    }
  }
}

interface AppRouteChildren {
  AppContributeRoute: typeof AppContributeRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAppsSlugRoute: typeof AppAppsSlugRoute
  AppBrowsePlatformRoute: typeof AppBrowsePlatformRoute
  AppFlowsIdRoute: typeof AppFlowsIdRoute
  AppSavedIdRoute: typeof AppSavedIdRoute
  AppScreensIdRoute: typeof AppScreensIdRoute
  AppSavedIndexRoute: typeof AppSavedIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContributeRoute: AppContributeRoute,
  AppReviewRoute: AppReviewRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAppsSlugRoute: AppAppsSlugRoute,
  AppBrowsePlatformRoute: AppBrowsePlatformRoute,
  AppFlowsIdRoute: AppFlowsIdRoute,
  AppSavedIdRoute: AppSavedIdRoute,
  AppScreensIdRoute: AppScreensIdRoute,
  AppSavedIndexRoute: AppSavedIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ApiV1AppsRouteChildren {
  ApiV1AppsSlugRoute: typeof ApiV1AppsSlugRoute
}

const ApiV1AppsRouteChildren: ApiV1AppsRouteChildren = {
  ApiV1AppsSlugRoute: ApiV1AppsSlugRoute,
}

const ApiV1AppsRouteWithChildren = ApiV1AppsRoute._addFileChildren(
  ApiV1AppsRouteChildren,
)

interface ApiV1CollectionsIdRouteChildren {
  ApiV1CollectionsIdItemsRoute: typeof ApiV1CollectionsIdItemsRoute
}

const ApiV1CollectionsIdRouteChildren: ApiV1CollectionsIdRouteChildren = {
  ApiV1CollectionsIdItemsRoute: ApiV1CollectionsIdItemsRoute,
}

const ApiV1CollectionsIdRouteWithChildren =
  ApiV1CollectionsIdRoute._addFileChildren(ApiV1CollectionsIdRouteChildren)

interface ApiV1CollectionsRouteChildren {
  ApiV1CollectionsIdRoute: typeof ApiV1CollectionsIdRouteWithChildren
}

const ApiV1CollectionsRouteChildren: ApiV1CollectionsRouteChildren = {
  ApiV1CollectionsIdRoute: ApiV1CollectionsIdRouteWithChildren,
}

const ApiV1CollectionsRouteWithChildren =
  ApiV1CollectionsRoute._addFileChildren(ApiV1CollectionsRouteChildren)

interface ApiV1FlowsRouteChildren {
  ApiV1FlowsIdRoute: typeof ApiV1FlowsIdRoute
}

const ApiV1FlowsRouteChildren: ApiV1FlowsRouteChildren = {
  ApiV1FlowsIdRoute: ApiV1FlowsIdRoute,
}

const ApiV1FlowsRouteWithChildren = ApiV1FlowsRoute._addFileChildren(
  ApiV1FlowsRouteChildren,
)

interface ApiV1KeysRouteChildren {
  ApiV1KeysIdRoute: typeof ApiV1KeysIdRoute
}

const ApiV1KeysRouteChildren: ApiV1KeysRouteChildren = {
  ApiV1KeysIdRoute: ApiV1KeysIdRoute,
}

const ApiV1KeysRouteWithChildren = ApiV1KeysRoute._addFileChildren(
  ApiV1KeysRouteChildren,
)

interface ApiV1ReviewRouteChildren {
  ApiV1ReviewKindIdRoute: typeof ApiV1ReviewKindIdRoute
}

const ApiV1ReviewRouteChildren: ApiV1ReviewRouteChildren = {
  ApiV1ReviewKindIdRoute: ApiV1ReviewKindIdRoute,
}

const ApiV1ReviewRouteWithChildren = ApiV1ReviewRoute._addFileChildren(
  ApiV1ReviewRouteChildren,
)

interface ApiV1ScreensRouteChildren {
  ApiV1ScreensIdRoute: typeof ApiV1ScreensIdRoute
}

const ApiV1ScreensRouteChildren: ApiV1ScreensRouteChildren = {
  ApiV1ScreensIdRoute: ApiV1ScreensIdRoute,
}

const ApiV1ScreensRouteWithChildren = ApiV1ScreensRoute._addFileChildren(
  ApiV1ScreensRouteChildren,
)

interface ApiV1RouteRouteChildren {
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1AppsRoute: typeof ApiV1AppsRouteWithChildren
  ApiV1CapturesRoute: typeof ApiV1CapturesRoute
  ApiV1CollectionsRoute: typeof ApiV1CollectionsRouteWithChildren
  ApiV1FlowsRoute: typeof ApiV1FlowsRouteWithChildren
  ApiV1KeysRoute: typeof ApiV1KeysRouteWithChildren
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1ReviewRoute: typeof ApiV1ReviewRouteWithChildren
  ApiV1SavesRoute: typeof ApiV1SavesRoute
  ApiV1ScreensRoute: typeof ApiV1ScreensRouteWithChildren
  ApiV1SearchRoute: typeof ApiV1SearchRoute
  ApiV1TaxonomyRoute: typeof ApiV1TaxonomyRoute
  ApiV1AdminMediaBackfillRoute: typeof ApiV1AdminMediaBackfillRoute
}

const ApiV1RouteRouteChildren: ApiV1RouteRouteChildren = {
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1AppsRoute: ApiV1AppsRouteWithChildren,
  ApiV1CapturesRoute: ApiV1CapturesRoute,
  ApiV1CollectionsRoute: ApiV1CollectionsRouteWithChildren,
  ApiV1FlowsRoute: ApiV1FlowsRouteWithChildren,
  ApiV1KeysRoute: ApiV1KeysRouteWithChildren,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1ReviewRoute: ApiV1ReviewRouteWithChildren,
  ApiV1SavesRoute: ApiV1SavesRoute,
  ApiV1ScreensRoute: ApiV1ScreensRouteWithChildren,
  ApiV1SearchRoute: ApiV1SearchRoute,
  ApiV1TaxonomyRoute: ApiV1TaxonomyRoute,
  ApiV1AdminMediaBackfillRoute: ApiV1AdminMediaBackfillRoute,
}

const ApiV1RouteRouteWithChildren = ApiV1RouteRoute._addFileChildren(
  ApiV1RouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  McpRoute: McpRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiV1RouteRoute: ApiV1RouteRouteWithChildren,
  ExtensionConnectRoute: ExtensionConnectRoute,
  MediaSplatRoute: MediaSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
