/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppContributeRouteImport } from './routes/_app/contribute'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as ExtensionConnectRouteImport } from './routes/extension.connect'
import { Route as MediaSplatRouteImport } from './routes/media/$'
import { Route as AppAppsSlugRouteImport } from './routes/_app/apps.$slug'
import { Route as AppBrowsePlatformRouteImport } from './routes/_app/browse.$platform'
import { Route as AppFlowsIdRouteImport } from './routes/_app/flows.$id'
import { Route as AppSavedIndexRouteImport } from './routes/_app/saved.index'
import { Route as AppSavedIdRouteImport } from './routes/_app/saved.$id'
import { Route as AppScreensIdRouteImport } from './routes/_app/screens.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContributeRoute = AppContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const ExtensionConnectRoute = ExtensionConnectRouteImport.update({
  id: '/extension/connect',
  path: '/extension/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppsSlugRoute = AppAppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowsePlatformRoute = AppBrowsePlatformRouteImport.update({
  id: '/browse/$platform',
  path: '/browse/$platform',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsIdRoute = AppFlowsIdRouteImport.update({
  id: '/flows/$id',
  path: '/flows/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedIndexRoute = AppSavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedIdRoute = AppSavedIdRouteImport.update({
  id: '/saved/$id',
  path: '/saved/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppScreensIdRoute = AppScreensIdRouteImport.update({
  id: '/screens/$id',
  path: '/screens/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/mcp': typeof McpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/contribute': typeof AppContributeRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/media/$': typeof MediaSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/apps/$slug': typeof AppAppsSlugRoute
  '/browse/$platform': typeof AppBrowsePlatformRoute
  '/flows/$id': typeof AppFlowsIdRoute
  '/saved/$id': typeof AppSavedIdRoute
  '/screens/$id': typeof AppScreensIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/saved/': typeof AppSavedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/contribute': typeof AppContributeRoute
  '/review': typeof AppReviewRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/media/$': typeof MediaSplatRoute
  '/docs': typeof DocsIndexRoute
  '/apps/$slug': typeof AppAppsSlugRoute
  '/browse/$platform': typeof AppBrowsePlatformRoute
  '/flows/$id': typeof AppFlowsIdRoute
  '/saved/$id': typeof AppSavedIdRoute
  '/screens/$id': typeof AppScreensIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/saved': typeof AppSavedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/mcp': typeof McpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/contribute': typeof AppContributeRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/media/$': typeof MediaSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/_app/apps/$slug': typeof AppAppsSlugRoute
  '/_app/browse/$platform': typeof AppBrowsePlatformRoute
  '/_app/flows/$id': typeof AppFlowsIdRoute
  '/_app/saved/$id': typeof AppSavedIdRoute
  '/_app/screens/$id': typeof AppScreensIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_app/saved/': typeof AppSavedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/mcp'
    | '/sign-in'
    | '/sign-up'
    | '/contribute'
    | '/review'
    | '/search'
    | '/settings'
    | '/docs/$slug'
    | '/extension/connect'
    | '/media/$'
    | '/docs/'
    | '/apps/$slug'
    | '/browse/$platform'
    | '/flows/$id'
    | '/saved/$id'
    | '/screens/$id'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/saved/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/sign-in'
    | '/sign-up'
    | '/contribute'
    | '/review'
    | '/search'
    | '/settings'
    | '/docs/$slug'
    | '/extension/connect'
    | '/media/$'
    | '/docs'
    | '/apps/$slug'
    | '/browse/$platform'
    | '/flows/$id'
    | '/saved/$id'
    | '/screens/$id'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/saved'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/docs'
    | '/mcp'
    | '/sign-in'
    | '/sign-up'
    | '/_app/contribute'
    | '/_app/review'
    | '/_app/search'
    | '/_app/settings'
    | '/docs/$slug'
    | '/extension/connect'
    | '/media/$'
    | '/docs/'
    | '/_app/apps/$slug'
    | '/_app/browse/$platform'
    | '/_app/flows/$id'
    | '/_app/saved/$id'
    | '/_app/screens/$id'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/_app/saved/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  McpRoute: typeof McpRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ExtensionConnectRoute: typeof ExtensionConnectRoute
  MediaSplatRoute: typeof MediaSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contribute': {
      id: '/_app/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof AppContributeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/extension/connect': {
      id: '/extension/connect'
      path: '/extension/connect'
      fullPath: '/extension/connect'
      preLoaderRoute: typeof ExtensionConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/apps/$slug': {
      id: '/_app/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppAppsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/$platform': {
      id: '/_app/browse/$platform'
      path: '/browse/$platform'
      fullPath: '/browse/$platform'
      preLoaderRoute: typeof AppBrowsePlatformRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows/$id': {
      id: '/_app/flows/$id'
      path: '/flows/$id'
      fullPath: '/flows/$id'
      preLoaderRoute: typeof AppFlowsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved/': {
      id: '/_app/saved/'
      path: '/saved'
      fullPath: '/saved/'
      preLoaderRoute: typeof AppSavedIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved/$id': {
      id: '/_app/saved/$id'
      path: '/saved/$id'
      fullPath: '/saved/$id'
      preLoaderRoute: typeof AppSavedIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screens/$id': {
      id: '/_app/screens/$id'
      path: '/screens/$id'
      fullPath: '/screens/$id'
      preLoaderRoute: typeof AppScreensIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppContributeRoute: typeof AppContributeRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAppsSlugRoute: typeof AppAppsSlugRoute
  AppBrowsePlatformRoute: typeof AppBrowsePlatformRoute
  AppFlowsIdRoute: typeof AppFlowsIdRoute
  AppSavedIdRoute: typeof AppSavedIdRoute
  AppScreensIdRoute: typeof AppScreensIdRoute
  AppSavedIndexRoute: typeof AppSavedIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContributeRoute: AppContributeRoute,
  AppReviewRoute: AppReviewRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAppsSlugRoute: AppAppsSlugRoute,
  AppBrowsePlatformRoute: AppBrowsePlatformRoute,
  AppFlowsIdRoute: AppFlowsIdRoute,
  AppSavedIdRoute: AppSavedIdRoute,
  AppScreensIdRoute: AppScreensIdRoute,
  AppSavedIndexRoute: AppSavedIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  McpRoute: McpRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ExtensionConnectRoute: ExtensionConnectRoute,
  MediaSplatRoute: MediaSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
